name: CI

on:
  push:

jobs:
  ci-test:
    runs-on: ubuntu-latest
    #
    # GitHubActionsで利用可能な権限
    #
    # URL
    #   - https://docs.github.com/ja/actions/using-jobs/assigning-permissions-to-jobs
    #
    # もし指定したら、それ以外は全てnoneになる
    #
    permissions:
      actions: none
      checks: write
      contents: read
      deployments: none
      id-token: none
      issues: none
      discussions: none
      packages: none
      pages: none
      pull-requests: write
      repository-projects: none
      security-events: none
      statuses: write
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v6
      - name: Javaの環境をセットアップ
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: '【mainブランチ】'
        if: github.ref == 'refs/heads/main'
        run: make test
        env:
          TZ: Asia/Tokyo
      - name: '【mainブランチ以外】'
        if: github.ref != 'refs/heads/main'
        run: make test
        env:
          TZ: Asia/Tokyo

  ci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v6
      - name: Javaの環境をセットアップ
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: make lint
        run: make lint
